POST http://localhost:5000/students
Content-Type: application/json

{
    "id":3,
    "name":"abhishek",
    "age":18,
    "rollno":18
}

###
GET http://localhost:5000/students

###
GET http://localhost:5000/student/3

###
PUT http://localhost:5000/students/3
Content-Type: application/json

{
    "id":4,
    "name":"anudeep",
    "age":19,
    "rollno":19
}

###
DELETE http://localhost:5000/students/4